### ISSUE TITLE
Is Aladdin a tool replace FPGA to design hardware accelerator?

### ISSUE THREAD

**Issue by HarrialX** [harvard-acc/ALADDIN#18]
I have seen most of accelerator works are finished by FPGA / ASIC / other hardware platforms, not purely completed in software level. Is ALADDIN a tool could design accelerator with inner-parallelism completely in software level? Not just some interfaces.

**Comment by xyzsam** [comment]
Aladdin is an accelerator *modeling* tool. FPGAs are used for accelerator prototyping and deployment. The idea is to use Aladdin to guide your hardware accelerator design space exploration and identity the optimal configuration that you eventually deploy on an FPGA. These tools are complementary and do not replace one another.
