### ISSUE TITLE
Error: can't find library python2.7 required by python

### ISSUE THREAD

**Issue by yangyl7239** [harvard-acc/ALADDIN#31]
root@972a8d761493:/workspace/gem5-aladdin# scons build/X86/gem5.opt
scons: Reading SConscript files ...
Warning: Your compiler doesn't support incremental linking and lto at the same time, so lto is being disabled. To force lto on anyway, use the --force-lto option. That will disable partial linking.
Checking for C header file Python.h... yes
Checking for C library python2.7... no
Error: can't find library python2.7 required by python

**Comment by xyzsam** [comment]
This is probably the same error as here:
https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/gem5-aladdin-users/IWtLUF4Pbw0/KaIXm4M5BgAJ
