### ISSUE TITLE
declare it as partition_factor 1 in your config file, like:   like what？

### ISSUE THREAD

**Issue by yangyl7239** [harvard-acc/ALADDIN#37]
Note that you need to explicitly config how to partition each array in your source code. If you do not want to partition the array, declare it as partition_factor 1 in your config file, like:

like what？

**Comment by xyzsam** [comment]
The general format is: `partition,cyclic,array_name,total_size,word_size,partition_factor`

Look at https://github.com/harvard-acc/ALADDIN/blob/master/integration-test/with-cpu/test_aes/test_aes.cfg for an example.
