### ISSUE TITLE
About the generation of binary files

### ISSUE THREAD

**Issue by yangyl7239** [harvard-acc/ALADDIN#38]
About 
https://github.com/harvard-acc/ALADDIN/blob/master/integration-test/with-cpu/test_aes/aes 
and 
https://github.com/harvard-acc/ALADDIN/blob/master/integration-test/with-cpu/test_aes/dynamic_trace.gz 
these two files. 
About these two files, After I modify the code corresponding to the aes algorithm in the MachSuite folder, how do I generate the 'aes' and 'dynamic_trace.gz' file corresponding to the new code?

**Comment by xyzsam** [comment]
See solution at https://groups.google.com/g/gem5-aladdin-users/c/lAx6GrhoY0Y/m/fwnVUTS9AAAJ.

Also, PR #39 fixes some bugs with the aes test.
