### ISSUE TITLE
Failed to build aladdin

### ISSUE THREAD

**Issue by peterhchen** [harvard-acc/ALADDIN#46]
Failed to Build on Ubuntu machine:
Program.cpp: In memeber function 'std::__cxx11::list<std::[air<comst ExecNode *. comst ExecNode*> > Program::findLoopBoundaries(const SrcTypes::UniqueLabel*, const ScrTypes::DynamicLabel*_const':
Program.cpp:76:19: crror: 'loop_start' may beused inintialized in this funtion [-Weorror-unitilized]
   cont ExecNode* loop_start;

![Build_err](https://user-images.githubusercontent.com/12787855/138229658-2e95a59c-c0ef-4e53-85a1-3a3af5e9aef9.png)

Peter H. Chen (peter.hp.chen@gmail.com)

**Comment by xyzsam** [comment]
Apologies for the late response; I did not see this issue until today. You need to pull the latest code. This issue was fixed in https://github.com/harvard-acc/ALADDIN/commit/448b8f41865003e20eee0bdbd7a73febb5c3abe3 over a year ago.
